### ISSUE TITLE
Disappearing walls and tiles over time in multiplayer

### ISSUE THREAD

**Issue by Borkius** [Tyfyter/BlockSwap#10]
With Thorium added (haven't tested others) swapped blocks disappear over time, replaced by what was replaced (eg: dirt, snow). This happens both infront of my eyes and when away from the area.

**Comment by Tyfyter** [comment]
Are all swapped tiles changed back when you save and exit?

**Comment by Tyfyter** [comment]
What exact version are you on?

**Comment by Darkmega18** [comment]
well, just now I downloaded the one from 9 hours ago: 1.0.8.
confirmed to still be occurring however.

**Comment by Tyfyter** [comment]
Do you have any mods other than block swap and thorium enabled?

**Comment by Darkmega18** [comment]
whoops. looking at wrong issue. xD sorry! I went through the discord's github pop-up without realizing.

**Comment by Borkius** [comment]
They do not return when I save and exit, and when I mine the blocks they drop what they visually are eg. dirt and snow.
I have other mods but I have only noticed this issue with Thorium, and when I disable Thorium from a large modpack I use the issue goes away. The version of Tmodloader I'm on is v.0.11.8.5 and the Terraria version is v1.3.5.3
My current modlist is:
Thorium
Spirit Mod
Mr Plague's Authentic Races
Magic Storage Extra
Vein Miner
Recipe Browser
Auto Trash
Shaggy's Addon Races
Boss Checklist
Omni Swing
Smart Doors
Item Frame Weapon Rack Fixer
Shorter Respawn Time
Ultimate Vanity Mod
Which Mod is This From?

As said I've only noticed this issue with Thorium but it's possible there's other mods on the mod browser that cause this that I don't use currently. I had Thorium and Calamity enabled in one world and when I disabled Thorium the issue stopped.

**Comment by Tyfyter** [comment]
I meant back to what they were before you swapped them, because in that case it'd just be that the tiles are only being swapped Client-Side and when grass grows or any other Server-Side random tile change occurs the client gets told what the affected block actually is and that replaces the desynced Client-Side block.

**Comment by Borkius** [comment]
The tiles\walls do not disappear and return to what they originally were when I leave the game and come back (at least not that I've noticed so far when I tested). The tiles\walls return to what they were originally even in multiplayer and I can see (and vice-versa) the returned blocks that another player also sees (even in real time as we both watch).

**Comment by Tyfyter** [comment]
So you're saying that in multiplayer if you (for example) replace a dirt block with wood all players see the dirt block being replaced by wood, but then it later becomes a grass block despite all players seeing it as wood until this point?

**Comment by Borkius** [comment]
Yeah, they also see it change back into dirt later. This happens with snow and dirt that doesn't grow grass too, and also background dirt walls.

**Comment by Borkius** [comment]
It also doesn't change all at once (the entirety of the replaced blocks), it changes over time. I'll come back to my house after exploring and half the floor is gone and replaced by dirt, and while I'm watching the other half will disappear.

**Comment by Tyfyter** [comment]
And judging by the information you initially provided, this happens with thorium enabled but not without it?

**Comment by Borkius** [comment]
Yep. I'll test some other big mods too while I'm at it.

**Comment by Borkius** [comment]
Oh I forgot to say, I also don't get the blocks back that get replaced.

**Comment by Borkius** [comment]
Ok well I re-enabled BlockSwap on my world with the same mods and now it's not doing the issue? Very strange. It's possible this starts happening over time with being in a world. Or maybe an update fixed it if you updates recently lol. I'll keep playing and see if it happens again.

**Comment by Tyfyter** [comment]
If it only occurred with Thorium enabled it seems likely that it was actually an issue with Thorium, since the tile changes from block swapping reaching other players means it couldn't be a client-server desync without heavy interference from another mod (much would also break vanilla mechanics)

**Comment by Borkius** [comment]
Alright. I'll update here if it starts happening again.

**Comment by Borkius** [comment]
So I just discovered the issue only happens in multiplayer. That's why I couldn't get it to happen again when playing singleplayer.

**Comment by Tyfyter** [comment]
Can you send the server log here?
I can't tell whether this is an incompatibility or just another mod's glitch without it

**Comment by Borkius** [comment]
I guess I was wrong all along. I just disabled all mods except BlockSwap and the issue is happening in multiplayer and not singleplayer. Sorry.
[server.log](https://github.com/Tyfyter/BlockSwap/files/7917308/server.log)

**Comment by Tyfyter** [comment]
Which block swap version are you on?

**Comment by Tyfyter** [comment]
Unless I misread the log you're using a different block swap mod, and iirc not even the latest version of it
