### ISSUE TITLE
When requiring multiple "Hits" to break a block, tiles are consumed despite not being placed.

### ISSUE THREAD

**Issue by Darkmega18** [Tyfyter/BlockSwap#11]
With a large cluster of mods I've got an issue where using block swap via tools which consume blocks to place other blocks like the living wood wand etc will consume and delete the material they use if the block they're replacing takes multiple hits with the wand to break before being replaced.

To replicate, if it will occur and is only blockswap doing it:

Place down a bunch of dirt.
get a low tier pickaxe.
try to place living wood using a living wood wand over the top of the dirt.
the dirt will take 2 or so hits to break and you'll consume two wood, but only place one down.

This is also a visible issue with different variations of planters and also furniture, but it weirdly only occurs when facing in certain directions.

For example i may place down a table, then accidentally blockswap a chair that I wanted in it's place because it was misaligned but instead the chair will get consumed and the table is unphased.

Planters in my case, using the simple daybloom planter, when going from right to left, I can rapidly place planters without them being destroyed. But going left to right for some reason the planters want to constantly replace themselves, this causes double tapping again as the tool tries to break the planter there before hand and place it over the existing one, resulting in a loss of planters due to nothing being replaced into it's location.

**Comment by Tyfyter** [comment]
Can you send your client.log file?

**Comment by Darkmega18** [comment]
here we are. sorry, was gonna get it. but was reporting another issue to someone else also which I noticed within it when taking a look for myself.
[client.log](https://github.com/Tyfyter/BlockSwap/files/7906238/client.log)

**Comment by Darkmega18** [comment]
```
[
  "Fargowiltas",
  "FargowiltasMusic",
  "FargowiltasSouls",
  "Split",
  "SpiritMod",
  "AAAAUThrowing",
  "Idglibrary",
  "SGAmod",
  "SubworldLibrary",
  "Luiafk",
  "BossChecklist",
  "CheatSheet",
  "AlchemistNPCLite",
  "BaseLibrary",
  "ContainerLibrary",
  "CrouchMod",
  "DNIWpnUpgr",
  "DualWielding",
  "FKBossHealthBar",
  "FluidLibrary",
  "FunctionalBlockSwap",
  "Gensokyo",
  "GensokyoMusic",
  "MagicStorageExtra",
  "MetroidMod",
  "PortableStorage",
  "PylonNPC",
  "RecipeBrowser",
  "Redemption",
  "RedemptionMusic",
  "SacredTools",
  "ShopExpander",
  "SolutionsMod",
  "StarsAbove",
  "StarsAboveMusic",
  "ThoriumMod",
  "TooManySlots",
  "VeinMiner",
  "WeaponOut",
  "WMITF",
  "WorldGenPreviewer",
  "PreHMTeleportation"
]
```

here is the enabled mods list, if theres anything to test against or you're curious.

edit: seems I just never noticed it before, but it's actually doing it for all tiles, including my building materials. not just wants etc. if it needs multi hits. it'll eat blocks for each hit. _(sorry, I replaced the name thinking it was some things, then went to test it, and it was all the things)_

**Comment by Darkmega18** [comment]
oh. I noticed there was a recent update. I'm going to get it to see if it still occurs.

edit: yeah, bug still occurs,

**Comment by Darkmega18** [comment]
noice, awesome, top job. now I can get back to building and not obsessing over inefficiencies eating my tiles.
