### ISSUE TITLE
Block Swapping issue with stack of furniture

### ISSUE THREAD

**Issue by zauberparacelsus** [Tyfyter/BlockSwap#9]
When holding a stack of a furniture item and trying to place it, the block swapper will sometimes immediately try to place another from the stack, breaking the already-placed one and putting in a new one.  I noticed that with blocks, the block swapper will avoid swapping a block if it would just be placing the same kind of block, so I guess that check isn't being performed for furniture?

**Comment by Tyfyter** [comment]
The check is being done with furniture, but vanilla furniture is generally just different frames of a single tile type, so every type of furniture that functions slightly differently ends up being a new edge case, what furniture types did this occur with?
